"""empty message

Revision ID: 3bdb9d3089e
Revises: None
Create Date: 2015-05-14 23:48:45.332205

"""

# revision identifiers, used by Alembic.
revision = '3bdb9d3089e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Productos',
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('idProducto'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('Acciones',
    sa.Column('idAccion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('idProducto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProducto'], ['Productos.idProducto'], ),
    sa.PrimaryKeyConstraint('idAccion'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('Actores',
    sa.Column('idActor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('idProducto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProducto'], ['Productos.idProducto'], ),
    sa.PrimaryKeyConstraint('idActor'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Objetivos',
    sa.Column('idObjetivo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('idProducto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProducto'], ['Productos.idProducto'], ),
    sa.PrimaryKeyConstraint('idObjetivo'),
    sa.UniqueConstraint('descripcion')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Objetivos')
    op.drop_table('Actores')
    op.drop_table('Acciones')
    op.drop_table('Productos')
    ### end Alembic commands ###
